auth:
  token: your-shared-token
proxies:
- healthCheck:
    intervalSeconds: 10
    maxFailed: 3
    path: /
    timeoutSeconds: 3
    type: http
  loadBalancer:
    group: headlamp
    groupKey: your-shared-key
  localIP: headlamp.kube-system.svc.cluster.local
  localPort: 80
  name: headlamp
  remotePort: 30080
  type: tcp
serverAddr: frps.example.com
serverPort: 7000
version: '1.0.0'
