apiVersion: kuttl.dev/v1beta1
kind: TestAssert
matchStyle: Exact
assert:
  # Assert the Provider exists
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-cloudflare
    spec:
      package: provider-cloudflare
      controllerConfigRef:
        name: default

  # Assert the ProviderConfig is correctly referencing the secret
  - apiVersion: cloudflare.upbound.io/v1beta1
    kind: ProviderConfig
    metadata:
      name: bt-cloudflare-providerconfig
    spec:
      credentials:
        source: Secret
        secretRef:
          name: argocd-secrets
          namespace: crossplane-system
          key: CLOUDFLARE_TOKEN_PROD
