apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: Zone
metadata:
  name: beckers-lab-dev-zone
spec:
  forProvider:
    plan: free
    type: full
    zone: beckers-lab.dev
  providerConfigRef:
    name: default
