apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-cloudflare
spec:
  controllerConfigRef:
    name: default
  package: provider-cloudflare
---
apiVersion: cloudflare.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: bt-cloudflare-providerconfig
spec:
  credentials:
    secretRef:
      key: CLOUDFLARE_TOKEN_PROD
      name: argocd-secrets
      namespace: crossplane-system
    source: Secret
