apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.crossplane.io/crossplane-contrib/provider-gcp:v1.14.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider-config
spec:
  credentials:
    secretRef:
      key: creds
      name: gcp-creds
      namespace: crossplane-system
    source: Secret
  projectID: your-gcp-project-id
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gcp-creds
  namespace: crossplane-system
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        recursive: false
        secretsPath: /gcp-creds
      serviceTokenSecretReference:
        secretName: infisical-token
        secretNamespace: default
  managedKubeSecretReferences:
  - creationPolicy: Orphan
    secretName: gcp-creds
    secretNamespace: crossplane-system
    secretType: Opaque
    template:
      data:
        creds: '{{ .GCP_CREDS_JSON.Value }}'
      includeAllSecrets: false
  resyncInterval: 60