apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
      version: '2.10.0'
  install:
    createNamespace: true
  interval: '10m'
  values:
    installCRDs: true