auth:
  token: OVERWRITEME!
proxies:
- healthCheck:
    intervalSeconds: 10
    maxFailed: 3
    path: /
    timeoutSeconds: 3
    type: http
  loadBalancer:
    group: k8s
    groupKey: OVERWRITEME!
  localIP: ingress-nginx-controller.kube-system.svc.cluster.local
  localPort: 80
  name: k8s-ingress
  remotePort: 30080
  type: tcp
serverAddr: frps.example.com
serverPort: 7000
version: '1.0.0'