apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-secrets-operator
  namespace: infisical
spec:
  chart:
    spec:
      chart: secrets-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: infisical
      version: '0.1.0'
  install:
    createNamespace: true
  interval: '10m'