apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-oidc-secret
  namespace: default
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        recursive: false
        secretsPath: /github-oidc-secret
      serviceTokenSecretReference:
        secretName: infisical-token
        secretNamespace: default
  managedKubeSecretReferences:
  - creationPolicy: Orphan
    secretName: github-oidc-secret
    secretNamespace: default
    secretType: Opaque
    template:
      data:
        clientID: '{{ .GITHUB_OIDC_CLIENT_ID.Value }}'
        clientSecret: '{{ .GITHUB_OIDC_CLIENT_SECRET.Value }}'
      includeAllSecrets: false
  resyncInterval: 60
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: frpc-auth-token
  namespace: kube-system
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        recursive: false
        secretsPath: /frpc-auth-token
      serviceTokenSecretReference:
        secretName: infisical-token
        secretNamespace: default
  managedKubeSecretReferences:
  - creationPolicy: Orphan
    secretName: frpc-auth-token
    secretNamespace: kube-system
    secretType: Opaque
    template:
      data:
        FRPC_AUTH_TOKEN: '{{ .FRPC_AUTH_TOKEN.Value }}'
      includeAllSecrets: false
  resyncInterval: 60