apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: build-nixos-image
spec:
  package: ghcr.io/your-org/builder:latest
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: do-nixos-droplet
spec:
  compositeTypeRef:
    apiVersion: infra.example.org/v1alpha1
    kind: XNixServer
  mode: Pipeline
  pipeline:
    - functionRef:
        name: build-nixos-image
      step: build-nixos-image
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: compute.digitalocean.crossplane.io/v1alpha1
              kind: Droplet
              metadata:
                name: nixos-droplet
              spec:
                forProvider:
                  image: placeholder
                  region: placeholder
                  size: s-1vcpu-1gb
                providerConfigRef:
                  name: default
                writeConnectionSecretToRef:
                  name: nixos-droplet-secret
                  namespace: default
            name: droplet
            patches:
              - combine:
                  strategy: string
                  string:
                    fmt: "%s|%s"
                  variables:
                    - fromFieldPath: context.imageSlug
                    - fromFieldPath: spec.region
                toFieldPath: spec.forProvider.image
                type: CombineFromComposite
              - fromFieldPath: spec.region
                toFieldPath: spec.forProvider.region
                type: FromCompositeFieldPath
      step: inject-droplet
