[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colored>=2.3.0",
    "kcl-lib>=0.11.2",
    "toml>=0.10.2",
]
