apiVersion: kuttl.dev/v1beta1
kind: TestAssert
matchStyle: Exact
assert:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: argocd

  - apiVersion: v1
    kind: Secret
    metadata:
      name: project-secrets
      namespace: crossplane-system
    data:
      test: "MTIzNDU=" # base64 for "12345", see secrets.json

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argo-cd-argocd-repo-server # runs the AVP plugin
      namespace: argocd

  - apiVersion: v1
    kind: Service
    metadata:
      name: argo-cd-argocd-server
      namespace: argocd
