apiVersion: kuttl.dev/v1beta1
kind: TestAssert
matchStyle: Subset
assert:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argo-cd-argocd-repo-server
      namespace: argocd
    spec:
      template:
        spec:
          containers:
            - name: avp
              image: ghcr.io/argoproj-labs/argocd-vault-plugin:v1.16.0
              env:
                - name: AVP_TYPE
                  value: sops
                - name: SOPS_AGE_KEY_FILE
                  value: /sops/keys.txt
              volumeMounts:
                - name: sops-key
                  mountPath: /sops
                - name: project-secrets
                  mountPath: /secrets
