apiVersion: kuttl.dev/v1beta1
kind: TestAssert
assert:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: crossplane
      namespace: crossplane-system
    spec:
      template:
        spec:
          containers:
            - name: crossplane
              args:
                - --enable-composition-functions
